### ISSUE TITLE
Preserve Attendee Metadata and Event Colors in Calendar Modifications

### ISSUE THREAD

**Issue by florisvlasveld** [taylorwilsdon/google_workspace_mcp#319]
## Is your feature request related to a problem? Please describe.

When using `modify_event` to add attendees (such as meeting room resources) to an existing calendar event, all attendee metadata is lost. Specifically:

1. **Attendee response statuses are reset** - All existing attendees have their `responseStatus` (accepted, declined, tentative) reset to `needsAction`, requiring everyone to re-accept the meeting
2. **Organizer and optional flags are lost** - The `organizer: true` and `optional: true` flags on attendees are not preserved
3. **Event colors are reset** - Custom event colors (`colorId`) are reset to the default calendar color

This happens because `modify_event` only accepts attendee email strings, not full attendee objects with metadata. This makes the tool unsuitable for common calendar operations like adding meeting rooms to existing events without disrupting all attendees.

## Describe the solution you'd like

Two changes would solve this:

1. **Accept attendee objects with metadata in `modify_event`:**
   ```python
   attendees=[
       {"email": "user@example.com", "responseStatus": "accepted", "organizer": True},
       {"email": "room@resource.calendar.google.com"}  # New attendee, status defaults to needsAction
   ]
   ```

2. **Preserve `colorId` during modifications:**
   Either preserve it automatically when not explicitly changed, or expose it in `get_events` output and accept it in `modify_event`.

Alternatively, add a dedicated function to respond to calendar events:
```python
respond_to_event(event_id, response="accepted")  # For the authenticated user
```

## Describe alternatives you've considered

- **Making two API calls** (read then write with preserved data): Not possible because `get_events` returns attendee details as formatted text, not structured data, and even if parsed, `modify_event` doesn't accept the objects.

## Additional context

This limitation was discovered while building a meeting room booking automation. The workflow is:
1. Fetch events for a date
2. Check room availability
3. Add room resource to event attendees

After step 3, all attendees receive new invitations and must re-accept, and any custom event colors are lost. For a busy calendar with many attendees, this creates significant disruption.

The Google Calendar API itself supports passing attendee objects with `responseStatus` in PATCH requests - the limitation is in the MCP wrapper layer.

**Comment by taylorwilsdon** [comment]
Hey there, I believe it's resolved here - https://github.com/taylorwilsdon/google_workspace_mcp/issues/313

Can you pull main and confirm? This is not released yet so you won't get the fix with a `uvx` run, but you can clone the repo and `uv run` instead

**Comment by florisvlasveld** [comment]
@taylorwilsdon I cloned the repo and ran with `uv run` build unfortunately the problem is still there. The attendees are preserved, but their acceptance status and the event color are not.

```
**Command**: /opt/homebrew/bin/uv                                                                                                                                               │
**Args**:run --project=/Users/XXX/Projects/google_workspace_mcp/ /Users/XXX/Projects/google_workspace_mcp/main.py --tools gmail drive calendar docs sheets slides --tool-tier extended
```

**Comment by taylorwilsdon** [comment]
Hm ok thanks for the quick reply, will take a look!

**Comment by florisvlasveld** [comment]
@taylorwilsdon I pulled main today and tested the fix. While the event color is now preserved, the participants attendance status is reset (the status of attendees that previously accepted the calendar invite as well as the acceptance status of the organizer are removed).
